<?php

/**
 * Test class for Models_Dryad.
 * Generated by PHPUnit on 2011-12-20 at 23:22:27.
 */
class Models_DryadTest extends Zend_Test_PHPUnit_ControllerTestCase {

    /**
     * @var Models_Dryad
     */
    protected $ob;

    protected function setUp() {
        $this->obj = new Models_Dryad;
        $adapter = new Zend_Http_Client_Adapter_Test();
        $this->http = new Zend_Http_Client();
    }

    protected function tearDown() {

    }

    public function testFetchrtifactIds() {
        $response = $this->obj->fetchArtifactIds("Otto, Sarah P.", $this->http);
        $this->assertContains(
                "10.5061/dryad.18",
                $response
                );
    }

}

?>
