<?php

require_once dirname(__FILE__) . '/../Updater.php';

/**
 * Test class for Updater.
 * Generated by PHPUnit on 2011-05-28 at 13:52:13.
 */
class UpdaterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Updater
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Updater;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
