<?php

require_once dirname(__FILE__) . '/../../Models/Report.php';

/**
 * Test class for Models_Report.
 * Generated by PHPUnit on 2011-06-24 at 20:33:30.
 */
class Models_ReportTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Models_Report
     */
    protected $showDir;
    protected $renderedDir;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->showDir = APP_PATH . '/Tests/data/by_artifactReturns';
        $this->renderedDir = APP_PATH . '/Tests/data/renderedReports';

    }
    protected function prepareReport($fileName){
        $loc = $this->showDir . '/' . $fileName;
        $showResult = file_get_contents($loc);

        $couch = new Tests_Fakes_Couch();
        $couch->setShowsToReturn(array($showResult));
        $report = new Models_Report($couch, "6");
        $report->fetch();

        return $report;
    }


    public function testGetBestIdentifierWithTitle() {
        $report = $this->prepareReport('6.json');
        $bestId = $report->getBestIdentifier();
        $this->assertEquals(
                "CrossRef + Mendeley + Slideshare",
                $bestId
                );
    }

    public function testGetBestIdentifierWithoutTitle() {
        $report = $this->prepareReport('6-without-title.json');
        $bestId = $report->getBestIdentifier();
        $this->assertEquals(
                "6",
                $bestId
                );
    }
    
    public function testGetCreatedAt(){
        $report = $this->prepareReport('6.json');
        $expected = array('CrossRef'=>'31 May, 2011', 'Mendeley'=>'31 May, 2011', 'SlideShare'=>'28 May, 2011');
        $this->assertEquals(
                $expected,
                $report->getLastUpdatedAt('j M, Y')
                );
    }

    public function testGetArtifactsCount() {
        $report = $this->prepareReport('6.json');
        $this->assertEquals(
                4,
                $report->getArtifactsCount()
                );

    }

    public function testRender() {
        $report = $this->prepareReport("6.json");
        $rendered = $report->render();
        $this->assertXmlStringEqualsXmlFile(
                $this->renderedDir .'/6.html',
                $rendered
                );

    }

}

?>
