<?php
    // set the stuff that'll go in the <head>:
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                     ->appendHttpEquiv('Content-Language', 'en-US');

    $stylesheets = array(
        'http://fonts.googleapis.com/css?family=Lobster+Two:400italic',
        './ui/main.css',
        './ui/homepage.css',
        './ui/report.css'
        );
    $scripts = array(
        'https://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js',
        './ui/js/json2.min.js',
        './ui/js/tinybox.js',
        './ui/js/jquery.headerlinks.js',
        'ui/js/jquery.tooltip.js',
        'ui/js/jquery.zclip.js',
        'ui/js/jquery.color.js',
        './ui/js/home-ui.js'
        );

    $this->headLink()->headLink(array(
        'rel' => 'favicon',
        'href' => './ui/favicon.ico'
    ));
    foreach ($stylesheets as $loc){
        $this->headLink()->appendStylesheet($loc);
    }
    foreach ($scripts as $loc){
        $this->headScript()->appendFile($loc);
    }
    $this->headTitle()->setSeparator(': ')->prepend('total-impact');
?>
<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <div id="header">
            <div class="wrapper">
                <h1><span class="loathsome-hack"></span><a href="/">total-impact</a><span class="loathsome-hack"></span></h1>
                <ul id="nav">
                    <li><a href="/about">about</a></li>
                    <li><a href="http://twitter.com/#!/totalImpactdev">twitter</a></li>
                </ul>
            </div>
        </div><!-- end header -->

        <?php echo $this->layout()->content ?>
        
        <div id="footer">
            <div class="wrapper">
                <div id="twitterfeed" class="footercol">

                    <!--<h2 class="grey" id="recent">Recent reports</h2>-->
                    <!-- https://twitter.com/about/resources/widgets/widget_search -->

                    <script src="http://widgets.twimg.com/j/2/widget.js"></script>
                    <script>
                        new TWTR.Widget({
                            version: 2,
                            type: 'search',
                            search: 'via @mytotalImpact',
                            interval: 30000,
                            subject: 'Latest tweeted reports:',
                            width: "100%",
                            height: 250,
                            theme: {
                                shell: {
                                    background: '#eeeeee',
                                    color: '#000'
                                },
                                tweets: {
                                    background: '#eeeeee',
                                    color: '#000',
                                    links: '#b20'
                                }
                            },
                            features: {
                                scrollbar: true,
                                loop: false,
                                live: true,
                                hashtags: true,
                                timestamp: true,
                                avatars: true,
                                toptweets: true,
                                behavior: 'all'
                            }
                        }).render().start();
                    </script>
                </div>
                <div class="recent-changes footercol">
                    <h4>Latest changes on <a href="https://github.com/mhahnel/Total-Impact/blob/master/CHANGES.md">GitHub</a></h4>
                    <?php /*
                    include_once "library/PHPMarkdownExtra1.2.4/markdown.php";
                    $fh = @fopen("CHANGES.md", "r");

                    $lines = "";
                    for ($i = 0; $i < 5; $i++) {
                        echo Markdown(fgets($fh));
                    #echo fgets($fh);
                    #echo $i;
                                        }
                    #@fclose($fh);
                    #$my_html = Markdown($lines);
                    #echo $my_html; 
                     */
                    ?>


                </div>
                <div class="altmetrics footercol">

                    an <a class="img" href="http://altmetrics.org" title="an altmetrics project"><img src="./ui/img/altmetrics_logo.png" alt="altmetrics" width="80"/></a> project.<br/>
                </div>
            </div>
        </div> <!-- end footer -->
        <script type="text/javascript">
            //Google Analytics code
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-23384030-1']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
    </body>
</html>