<?php
require_once dirname(__FILE__) . '/couchDbTestCase.php';
/**
 * Test class for couchdb_Test.
 * Generated by PHPUnit on 2011-12-23 at 06:04:54.
 */
class couchdb_TestTest extends couchDbTestCase {

    public function testBy_nameWorksForPubMed() {
        $result = $this->couch
                ->key(array("PubMed", "0000000002"))
                ->getView("main", "by_name");
        print_r($result);

        $resultId = ($result->rows) ? $result->rows[0]->id : false;
        $this->assertEquals(
                "2",
                $resultId
                );


    }


}

?>
