<?php

require_once dirname(__FILE__) . '/../../../../application/Models/Provider/MendeleyProfile.php';

/**
 * Test class for Models_Provider_MendeleyProfile.
 * Generated by PHPUnit on 2011-12-22 at 06:43:47.
 */
class Models_Provider_MendeleyGroupTest extends PHPUnit_Framework_TestCase {

    protected $obj;

    protected function setUp() {
        $this->obj = new Models_Provider_MendeleyGroup();
        $adapter = new Zend_Http_Client_Adapter_Test();
        $this->http = new Zend_Http_Client();
        $this->creds = new Zend_Config_Ini(APPLICATION_PATH . '/config/creds.ini');
    }


    public function testFetchLinks() {
        $response = $this->obj->fetchLinks("530031", $this->http, $this->creds);
        print_r($response);
        $this->assertContains(
                array("namespace"=>"Mendeley", "id" => "b1684880-6724-11e0-a2d8-0024e8453de6"),
                $response
                );
    }
}
?>
