<?php

require_once dirname(__FILE__) . '/../../../../application/Models/Provider/MendeleyProfile.php';

/**
 * Test class for Models_Provider_MendeleyProfile.
 * Generated by PHPUnit on 2011-12-22 at 06:43:47.
 */
class Models_Provider_GitHubUserTest extends PHPUnit_Framework_TestCase {

    protected $obj;

    protected function setUp() {
        $this->obj = new Models_Provider_GitHubUser();
        $adapter = new Zend_Http_Client_Adapter_Test();
        $this->http = new Zend_Http_Client();
        $this->creds = new Zend_Config_Ini(APPLICATION_PATH . '/config/creds.ini');
    }


    public function testFetchLinks() {
        $response = $this->obj->fetchLinks("egonw", $this->http, $this->creds);
        $this->assertContains(
                "http://github.com/egonw/gtd",
                $response
                );
    }
}
?>
